services:
  - type: web
    name: licitabot-cloud
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ACCESS_PASSWORD
        value: 1234         # troque depois
      - key: ADMIN_UPLOAD_TOKEN
        value: admin123     # troque depois
      - key: SECRET_KEY
        generateValue: true

